In [1]:
import pandas as pd

In [2]:
sl = pd.read_excel(
    "./../../upgrade_mandi/shelf-life/Summer 2026 PUNE City Shelf Life.xlsx", "Sheet1"
)
sl.columns = sl.iloc[0]
sl = sl.iloc[1:]


nx_sl = pd.read_excel("./../../upgrade_mandi/nx/NX Article SL (1).xlsx", "Sheet1")


sl.columns = sl.columns.str.strip()
nx_sl.columns = nx_sl.columns.str.strip()

In [3]:
sl.columns

Index(['Sl.No', 'Article Code', 'Article Name', 'UoM', 'Category 1', 'Sub Cat',
       'Symbol', 'DSD', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
       'Friday', 'Saturday', 'Changes'],
      dtype='str', name=0)

In [4]:
nx_sl

,Sl.No,ITEM_CODE,SKU Name,Type,SL,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
0,1,1296,TENDER COCONUT 1.00 PIECE,NX,6,7,1,2,3,4,5,6
1,2,1284,INDIAN TOMATO (TAMATAR) 500.00 G,NX,6,7,1,2,3,4,5,6
2,3,1005,ROBUSTA BANANA 4.00 PIECES,NX,6,7,1,2,3,4,5,6
3,4,45306,POMEGRANATE 3.00 PIECES,NX,6,7,1,2,3,4,5,6
4,5,2116,ONION (KANDA) 1.00 KG,NX,6,7,1,2,3,4,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...
368,369,993186,Imported Snacky Apple,NX,6,7,1,2,3,4,5,6
369,370,7456,Thomson green grapes,NX,6,7,1,2,3,4,5,6
370,371,17043,Ready To eat premium mango,NX,6,7,1,2,3,4,5,6
371,372,17041,Alphonso Mango,NX,6,7,1,2,3,4,5,6
372,373,663048,Thomson green grapes,NX,6,7,1,2,3,4,5,6

In [5]:
day_of_the_week = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
]

# sl.drop(
#     columns=[
#         "Sunday",
#         "Monday",
#         "Tuesday",
#         "Wednesday",
#         "Thursday",
#         "Friday",
#         "Saturday",
#     ]
# )

nx_sl[
    [
        "ITEM_CODE",
    ]
    + day_of_the_week
].columns
# nx_sl.columns

Index(['ITEM_CODE', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
       'Friday', 'Saturday'],
      dtype='str')

In [6]:
formated_sl = pd.concat(
    [
        pd.DataFrame([{col: col for col in sl.columns}]),
        sl.merge(
            nx_sl["ITEM_CODE"],
            how="left_anti",
            left_on="Article Code",
            right_on="ITEM_CODE",
        ).drop(columns=["ITEM_CODE"]),
        (
            nx_sl[
                [
                    "ITEM_CODE",
                ]
                + day_of_the_week
            ]
            .merge(
                sl.drop(columns=day_of_the_week),
                how="inner",
                right_on="Article Code",
                left_on="ITEM_CODE",
            )
            .drop(columns=["ITEM_CODE"])
        ),
    ]
)

In [7]:
formated_sl.to_excel(
    "./../../upgrade_mandi/shelf-life/Shelf-Life_30-July-2026.xlsx", index=False
)

In [8]:
nx_sl

,Sl.No,ITEM_CODE,SKU Name,Type,SL,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
0,1,1296,TENDER COCONUT 1.00 PIECE,NX,6,7,1,2,3,4,5,6
1,2,1284,INDIAN TOMATO (TAMATAR) 500.00 G,NX,6,7,1,2,3,4,5,6
2,3,1005,ROBUSTA BANANA 4.00 PIECES,NX,6,7,1,2,3,4,5,6
3,4,45306,POMEGRANATE 3.00 PIECES,NX,6,7,1,2,3,4,5,6
4,5,2116,ONION (KANDA) 1.00 KG,NX,6,7,1,2,3,4,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...
368,369,993186,Imported Snacky Apple,NX,6,7,1,2,3,4,5,6
369,370,7456,Thomson green grapes,NX,6,7,1,2,3,4,5,6
370,371,17043,Ready To eat premium mango,NX,6,7,1,2,3,4,5,6
371,372,17041,Alphonso Mango,NX,6,7,1,2,3,4,5,6
372,373,663048,Thomson green grapes,NX,6,7,1,2,3,4,5,6

In [9]:
formated_sl[["Article Code"]].merge(
    nx_sl, how="inner", left_on="Article Code", right_on="ITEM_CODE"
).describe()

,Sl.No,ITEM_CODE,SL,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
count,371.000000,371.000000,371.0,371.0,371.0,371.0,371.0,371.0,371.0,371.0
mean,186.703504,60208.396226,6.0,7.0,1.0,2.0,3.0,4.0,5.0,6.0
std,107.631571,159570.765320,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,1.000000,997.000000,6.0,7.0,1.0,2.0,3.0,4.0,5.0,6.0
25%,93.500000,5113.500000,6.0,7.0,1.0,2.0,3.0,4.0,5.0,6.0
50%,187.000000,8544.000000,6.0,7.0,1.0,2.0,3.0,4.0,5.0,6.0
75%,279.500000,18878.500000,6.0,7.0,1.0,2.0,3.0,4.0,5.0,6.0
max,373.000000,956524.000000,6.0,7.0,1.0,2.0,3.0,4.0,5.0,6.0