In [70]:
import pandas as pd

import numpy as np

from utils.utils import nameExtracter

In [71]:
df = pd.read_excel("./../data/raw/B2B/B2B Daily Update sheet.xlsx", sheet_name="Sheet1")

df.columns = [i.strip().title() for i in df.columns]
df = (
    df.dropna(how="all")
    .drop(
        labels=["Sr No", "Total Amount", "Overall"],
        axis=1,
    )
    .dropna(how="all")
)

In [72]:
def formatDate(row: pd.Series) -> pd.Timestamp | float:
    try:
        return pd.to_datetime(row["Date"])
    except:
        return np.nan


df["Date"] = df.apply(formatDate, axis=1).ffill()

In [73]:
df.dropna(subset=df.columns.difference(["Date"]), how="all", inplace=True)

In [74]:
df[["Name", "Address"]] = (
    df[["Name", "Address"]]
    .ffill()
    .apply(
        lambda srs: pd.Series(
            name=srs.name, data=[str(string).title() for string in srs]
        ),
        axis=1,
    )
)

df["Item Name"] = df["Item Name"].apply(lambda name: str(name).title())

In [75]:
df

,Date,Name,Address,Item Name,Qty,Rate,Total Payment
2,2025-09-14,Manoj Jaiswal,Sadar,G4 Potato Retail,100.0,23.75,2375.0
3,2025-09-14,Manoj Jaiswal,Sadar,Red Onion Premium Retail,100.0,18.75,1875.0
5,2025-09-14,Jagdish Shahu,Besa,Agra Potato Premium Retail,50.0,21.25,1062.5
6,2025-09-14,Jagdish Shahu,Besa,Red Onion Premium Retail,50.0,18.75,937.5
8,2025-09-14,Mangesh Mankar,Jaitala,Agra Potato Premium Retail,50.0,21.25,1062.5
...,...,...,...,...,...,...,...
540,2025-10-01,Bhiwa Kawle,Laxmi Nagar,Red Onion Premium Retail,50.0,18.95,947.5
542,2025-10-01,Omprakash Shahu,Hingna,Agra Potato Premium Wholesale,50.0,17.00,850.0
545,2025-10-01,Shekhar,Kalamna,Potato B,50.0,10.00,500.0
546,2025-10-01,Shekhar,Kalamna,Onion B,50.0,10.00,500.0
547,2025-10-01,Shekhar,Kalamna,Garlic B,5.0,70.00,350.0

In [76]:
lst = [
    "Red Onion Premium Wholesale",
    "Red Onion Premium Retail",
    "White onion Wholesale",
    "White onion Retail",
    "Agra potato Premium Wholesale",
    "Agra Potato Premium Retail",
    "Agra Potato Retail Big",
    "G4 potato Wholesale",
    "G4 Potato Retail",
    "Ginger Banglore",
    "Garlic Regular",
    "Garlic Bolder",
    "Onion B",
    "Potato B",
    "Ginger B",
    "White Onion B",
    "Potato Small",
]

In [77]:
df = df.dropna(
    subset=[
        "Item Name",
    ],
    how="all",
)

In [78]:
df

,Date,Name,Address,Item Name,Qty,Rate,Total Payment
2,2025-09-14,Manoj Jaiswal,Sadar,G4 Potato Retail,100.0,23.75,2375.0
3,2025-09-14,Manoj Jaiswal,Sadar,Red Onion Premium Retail,100.0,18.75,1875.0
5,2025-09-14,Jagdish Shahu,Besa,Agra Potato Premium Retail,50.0,21.25,1062.5
6,2025-09-14,Jagdish Shahu,Besa,Red Onion Premium Retail,50.0,18.75,937.5
8,2025-09-14,Mangesh Mankar,Jaitala,Agra Potato Premium Retail,50.0,21.25,1062.5
...,...,...,...,...,...,...,...
540,2025-10-01,Bhiwa Kawle,Laxmi Nagar,Red Onion Premium Retail,50.0,18.95,947.5
542,2025-10-01,Omprakash Shahu,Hingna,Agra Potato Premium Wholesale,50.0,17.00,850.0
545,2025-10-01,Shekhar,Kalamna,Potato B,50.0,10.00,500.0
546,2025-10-01,Shekhar,Kalamna,Onion B,50.0,10.00,500.0
547,2025-10-01,Shekhar,Kalamna,Garlic B,5.0,70.00,350.0

In [79]:
df.to_excel("./../data/processed/B2B/Transaction List.xlsx", index=False)

In [80]:
grp = df.groupby(["Date"])

grp_names = list(grp.groups.keys())
ne = grp_names[4]
ne, df[df["Date"] == ne].sort_values("Item Name")[
    ["Date", "Item Name", "Rate"]
].groupby("Item Name")["Rate"].unique()

(Timestamp('2025-09-18 00:00:00'),
 Item Name
 Agra Potato Premium Retail     [21.0, 21.25]
 B Potato                              [10.0]
 G4 Big                                [15.0]
 G4 Potato Retail                      [21.0]
 Garlic Bolder                        [120.0]
 Garlic Regular                [100.0, 105.0]
 Ginger Banglore                 [80.0, 85.0]
 Onion B                               [10.0]
 Red Onion Premium Retail      [18.55, 18.75]
 White Onion Retail                    [30.0]
 Name: Rate, dtype: object)