In [ ]:
import email
import imaplib
import re
from datetime import datetime
from io import BytesIO

from os.path import join

from pathlib import Path

import camelot
import pandas as pd
from bs4 import BeautifulSoup

from glob import glob

In [2]:
prev = 0


def pretty(label: str, completed: float, total: int, length: int = 30) -> None:
    global prev
    print(
        " " * (prev * 2)
        + f"\r{label} ["
        + "=" * int(completed / total * length)
        + "-" * int((total - completed) / total * length)
        + f"] {int(completed / total * 100)}%",
        end="",
    )
    prev = length


def prettyPrintReplace(label: str) -> None:
    global prev
    label = str(label)
    print((" " * (prev * 2)) + f"\r{label}", end="")
    prev = len(label)

In [3]:
# Login credentials
IMAP_HOST = "imap.gmail.com"
EMAIL_USER = "ankushmisal7387@gmail.com"
EMAIL_PASS = "lnfv cnrn yrju ukom"

In [4]:
subject_to_search = "UPGRADE MANDI - Hyperpure"

In [5]:
# Connect and login
mail = imaplib.IMAP4_SSL(IMAP_HOST)
mail.login(EMAIL_USER, EMAIL_PASS)
mail.select("inbox")

statusRaw, messagesRaw = mail.search(None, f'(SUBJECT "{subject_to_search}")')

In [6]:
grnPrDF = pd.DataFrame(
    {"Cut/Veg": [], "Date": [], "GRN": [], "PO Amount": [], "Error": []}
)

status = statusRaw
messages = messagesRaw
total_mails = len(messages[0].split())
if status == "OK":
    for num in messages[0].split():
        typ, data = mail.fetch(num, "(RFC822)")
        msg = email.message_from_bytes(data[0][1])
        sub = msg["Subject"]
        prettyPrintReplace(f"Count: {len(grnPrDF) + 1}/{total_mails} {sub}")

        processedDOMTree = ""
        cutVeg = {"value": None}

        subject = re.sub("\s+", " ", msg["subject"])
        indexPO = re.search(r"CPCMH\d{2}-PO-\d{7}", subject)

        isGrnAmount = "UPGRADE MANDI - Hyperpure GRN against PO Number" in subject
        # print(isGrnAmount)
        isTotalAmount = "UPGRADE MANDI - Hyperpure PO Number" in subject

        if indexPO:
            indexPO = indexPO.group()
        else:
            raise Exception("Can't find PO number from mail.")

        if indexPO not in grnPrDF.index:
            grnPrDF.loc[indexPO] = ["", "", 0.0, 0.0, ""]

        for part in msg.walk():
            content_type = part.get_content_type()
            content_disposition = str(part.get("Content-Disposition") or "")

            if part.get_content_maintype() == "multipart":
                continue
            elif content_type == "application/pdf":
                # cutVeg = "VEG"

                pdfFileData = part.get_payload(decode=True)
                pdfFileStream = BytesIO(pdfFileData)

                # print(sub.split(" ")[-1])

                try:
                    with open(
                        join(
                            "dump", f"{indexPO} - {'GRN' if isGrnAmount else 'PO'}.pdf"
                        ),
                        "wb",
                    ) as f:
                        f.write(pdfFileStream.getbuffer())
                except IOError:
                    cutVeg = "Error"
                except Exception as e:
                    print("Other error")
                    print(e)
                    print(sub)

                # grnPrDF.loc[indexPO, "Cut/Veg"] = cutVeg
            elif content_type == "text/html":
                rawHTMLText = part.get_payload(decode=True).decode()

                processedDOMTree = BeautifulSoup(rawHTMLText, "html.parser")
                try:
                    amountDate = datetime.strptime(
                        processedDOMTree.find_all("table")[1]
                        .find_all("tr")[3]
                        .find_all("td")[1]
                        .find("span")
                        .text,
                        "%d %b %Y",
                    ).strftime("%d-%m-%Y")

                    amount = float(
                        processedDOMTree.find_all("table")[1]
                        .find_all("tr")[4]
                        .find_all("td")[1]
                        .find("span")
                        .text
                    )

                    if isGrnAmount:
                        grnPrDF.loc[indexPO, "GRN"] += amount
                    if isTotalAmount:
                        grnPrDF.loc[indexPO, "PO Amount"] += amount
                    grnPrDF.loc[indexPO, "Date"] = amountDate
                except Exception as e:
                    grnPrDF.loc[indexPO, "Error"] += f"{e};;"
                    pass

        # print(
        #     f"Date: {amountDate}",
        #     f"Index PO: {indexPO}",
        #     f'GRN total: {grnPrDF.iloc[-1]["GRN"]}',
        #     f'Total: {grnPrDF.iloc[-1]["PO Amount"]}',
        #     f'Cut: {grnPrDF.iloc[-1]["Cut/Veg"]}',
        #     sep="\n",
        #     end="\n\n\n",
        # )

Count: 560/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number34
Count: 561/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number76
Count: 562/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number18
Count: 563/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number32
Count: 564/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number32
Count: 565/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number57
Count: 566/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number53
Count: 567/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number08
Count: 568/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number12
Count: 569/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number27
Count: 570/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number94
Count: 571/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number35
Count: 572/1161 UPGRADE MANDI	 - Hyperpure - Hyperpure PO Scheduled for PO Number
Count: 572/1161 UPGRADE MANDI	 - Hyperpure GRN against PO Number CPCMH26-PO-2256775

In [31]:
grnPrDF.index.name = "PO Number"
grnPrDF.to_csv("./GRN PR (Blinkit).csv", index=True)

In [24]:
grnPrDF

,PO Amount,Cut/Veg,Date,GRN,PO Amount,Error
PO Number,,,,,,
0,CPCMH25-PO-1269666,NaN,05-12-2024,18788.5,18806.0,NaN
1,CPCMH25-PO-1274368,NaN,07-12-2024,3679.5,3679.5,NaN
2,CPCMH25-PO-1276694,NaN,08-12-2024,12899.5,12956.5,NaN
3,CPCMH25-PO-1279272,NaN,09-12-2024,9014.0,9028.0,NaN
4,CPCMH25-PO-1281280,NaN,10-12-2024,52301.7,55274.2,NaN
...,...,...,...,...,...,...
566,CPCMH26-PO-2244427,NaN,03-10-2025,7863.0,15268.5,list index out of range;;
567,CPCMH26-PO-2248894,NaN,04-10-2025,14854.4,26797.0,list index out of range;;
568,CPCMH26-PO-2252935,NaN,05-10-2025,17686.8,23482.2,list index out of range;;
569,CPCMH26-PO-2256775,NaN,06-10-2025,19440.0,23255.0,list index out of range;;
570,CPCMH26-PO-2256779,NaN,06-10-2025,13247.0,20202.0,list index out of range;;

In [34]:
grnPrDF = pd.read_csv("./GRN PR (Blinkit).csv")
grnPrDF.index = grnPrDF["PO Amount"]
grnPrDF.drop(columns=["PO Amount"], inplace=True)

In [35]:
grnPrDF

,PO Number,Cut/Veg,Date,GRN,PO Amount.1,Error
PO Amount,,,,,,
CPCMH25-PO-1269666,CPCMH25-PO-1269666,NaN,05-12-2024,18788.5,18806.0,NaN
CPCMH25-PO-1274368,CPCMH25-PO-1274368,NaN,07-12-2024,3679.5,3679.5,NaN
CPCMH25-PO-1276694,CPCMH25-PO-1276694,NaN,08-12-2024,12899.5,12956.5,NaN
CPCMH25-PO-1279272,CPCMH25-PO-1279272,NaN,09-12-2024,9014.0,9028.0,NaN
CPCMH25-PO-1281280,CPCMH25-PO-1281280,NaN,10-12-2024,52301.7,55274.2,NaN
...,...,...,...,...,...,...
CPCMH26-PO-2244427,CPCMH26-PO-2244427,NaN,03-10-2025,7863.0,15268.5,list index out of range;;
CPCMH26-PO-2248894,CPCMH26-PO-2248894,NaN,04-10-2025,14854.4,26797.0,list index out of range;;
CPCMH26-PO-2252935,CPCMH26-PO-2252935,NaN,05-10-2025,17686.8,23482.2,list index out of range;;
CPCMH26-PO-2256775,CPCMH26-PO-2256775,NaN,06-10-2025,19440.0,23255.0,list index out of range;;
CPCMH26-PO-2256779,CPCMH26-PO-2256779,NaN,06-10-2025,13247.0,20202.0,list index out of range;;

In [36]:
file_list = glob(join("dump", "*.pdf"))
file_list = list(filter(lambda x: ("GRN.pdf" in x) or ("PO.pdf" in x), file_list))
ln = len(file_list)
for i, path in enumerate(file_list):
    cutVeg = "VEG"
    # print(f'"{grnPrDF.loc[Path(path).stem.split(" - ")[0], "Cut/Veg"]}"')
    if str(grnPrDF.loc[Path(path).stem.split(" - ")[0], "Cut/Veg"]) != "nan":
        continue

    try:
        pdfParserObject = camelot.read_pdf(path)
        if len(pdfParserObject[0].df) >= 5:
            findCut = pdfParserObject[0].df.iloc[5][1]
            findMatches = re.findall(r".*cut.*", findCut, re.IGNORECASE)
            if len(findMatches) != 0:
                cutVeg = "CUT-VEG"
    except:
        cutVeg = "Error"
    grnPrDF.loc[Path(path).stem.split(" - ")[0], "Cut/Veg"] = cutVeg
    print(
        f"{i + 1}/{ln}, {Path(path).stem.split( ' - ')[0]}, {findMatches}, {grnPrDF.loc[Path(path).stem.split(' - ')[0], 'Cut/Veg']}"
    )
    # if i > 100:
    #     break

C:\Users\cw\AppData\Local\Temp\ipykernel_15292\2237780842.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'VEG' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  grnPrDF.loc[Path(path).stem.split(" - ")[0], "Cut/Veg"] = cutVeg

1/1129, CPCMH25-PO-1269666, [], VEG
3/1129, CPCMH25-PO-1274368, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
5/1129, CPCMH25-PO-1276694, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
7/1129, CPCMH25-PO-1279272, [], VEG
9/1129, CPCMH25-PO-1281280, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
11/1129, CPCMH25-PO-1283870, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
13/1129, CPCMH25-PO-1286137, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
15/1129, CPCMH25-PO-1288444, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
17/1129, CPCMH25-PO-1290703, [], VEG
18/1129, CPCMH25-PO-1291612, [], VEG
20/1129, CPCMH25-PO-1293847, [], VEG
22/1129, CPCMH25-PO-1294697, [], VEG
24/1129, CPCMH25-PO-1295966, [], VEG
26/1129, CPCMH25-PO-1296693, [], VEG
28/1129, CPCMH25-PO-1298679, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
30/1129, CPCMH25-PO-1300959, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
32/1129, CPCMH25-PO-1302565, [], VEG
33/1129, CPCMH25-PO-1303813, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
35/1129, CPCMH25-PO-1306159, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
37/1129, CPCMH25-PO-1308748, [], VEG
39/1129, CPCMH25-PO-1309503, [], VEG
41/1129, CPCMH25-PO-1310923, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
43/1129, CPCMH25-PO-1313063, [], VEG
45/1129, CPCMH25-PO-1315544, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
47/1129, CPCMH25-PO-1318159, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
49/1129, CPCMH25-PO-1319334, [], VEG
51/1129, CPCMH25-PO-1320789, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
53/1129, CPCMH25-PO-1321537, [], VEG
55/1129, CPCMH25-PO-1323259, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
57/1129, CPCMH25-PO-1323269, [], VEG
59/1129, CPCMH25-PO-1325602, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
61/1129, CPCMH25-PO-1325618, [], VEG
63/1129, CPCMH25-PO-1326787, [], VEG
65/1129, CPCMH25-PO-1327893, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
67/1129, CPCMH25-PO-1327906, [], VEG
69/1129, CPCMH25-PO-1330151, [], VEG
71/1129, CPCMH25-PO-1330232, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
73/1129, CPCMH25-PO-1332836, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
75/1129, CPCMH25-PO-1332840, [], VEG
77/1129, CPCMH25-PO-1335331, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
79/1129, CPCMH25-PO-1335693, [], VEG
81/1129, CPCMH25-PO-1336345, [], VEG
83/1129, CPCMH25-PO-1338180, [], VEG
85/1129, CPCMH25-PO-1338211, [], VEG
87/1129, CPCMH25-PO-1340676, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
89/1129, CPCMH25-PO-1341925, [], VEG
91/1129, CPCMH25-PO-1342926, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
93/1129, CPCMH25-PO-1345149, [], VEG
95/1129, CPCMH25-PO-1347489, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
97/1129, CPCMH25-PO-1349975, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
99/1129, CPCMH25-PO-1352526, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
101/1129, CPCMH25-PO-1355936, [], VEG
103/1129, CPCMH25-PO-1357263, [], VEG
105/1129, CPCMH25-PO-1359757, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
107/1129, CPCMH25-PO-1361923, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
109/1129, CPCMH25-PO-1364176, [], VEG
111/1129, CPCMH25-PO-1366628, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
113/1129, CPCMH25-PO-1371083, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
115/1129, CPCMH25-PO-1371193, [], VEG
116/1129, CPCMH25-PO-1372026, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
118/1129, CPCMH25-PO-1374808, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
120/1129, CPCMH25-PO-1377305, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
122/1129, CPCMH25-PO-1379541, [], VEG
124/1129, CPCMH25-PO-1381743, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
126/1129, CPCMH25-PO-1384574, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
128/1129, CPCMH25-PO-1386433, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
130/1129, CPCMH25-PO-1388984, [], VEG
132/1129, CPCMH25-PO-1391578, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
134/1129, CPCMH25-PO-1394135, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
136/1129, CPCMH25-PO-1396369, [], VEG
138/1129, CPCMH25-PO-1398408, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
140/1129, CPCMH25-PO-1398891, [], VEG
142/1129, CPCMH25-PO-1401205, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
144/1129, CPCMH25-PO-1403816, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
146/1129, CPCMH25-PO-1406301, [], VEG
148/1129, CPCMH25-PO-1409340, [], VEG
150/1129, CPCMH25-PO-1410605, [], VEG
152/1129, CPCMH25-PO-1411919, [], VEG
154/1129, CPCMH25-PO-1412435, [], VEG
155/1129, CPCMH25-PO-1413212, [], VEG
157/1129, CPCMH25-PO-1414391, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
159/1129, CPCMH25-PO-1414700, [], VEG
161/1129, CPCMH25-PO-1416629, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
163/1129, CPCMH25-PO-1419545, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
165/1129, CPCMH25-PO-1422314, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
167/1129, CPCMH25-PO-1425081, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
169/1129, CPCMH25-PO-1427810, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
171/1129, CPCMH25-PO-1430737, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
173/1129, CPCMH25-PO-1433222, [], VEG
175/1129, CPCMH25-PO-1435532, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
177/1129, CPCMH25-PO-1438375, [], VEG
179/1129, CPCMH25-PO-1441280, [], VEG
181/1129, CPCMH25-PO-1444138, [], VEG
183/1129, CPCMH25-PO-1446805, [], VEG
185/1129, CPCMH25-PO-1449624, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
187/1129, CPCMH25-PO-1452154, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
189/1129, CPCMH25-PO-1454747, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
191/1129, CPCMH25-PO-1455612, [], VEG
193/1129, CPCMH25-PO-1457511, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
195/1129, CPCMH25-PO-1460289, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
197/1129, CPCMH25-PO-1462921, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
199/1129, CPCMH25-PO-1463502, [], VEG
201/1129, CPCMH25-PO-1465695, [], VEG
203/1129, CPCMH25-PO-1468328, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
205/1129, CPCMH25-PO-1470780, [], VEG
207/1129, CPCMH25-PO-1471400, [], VEG
209/1129, CPCMH25-PO-1473321, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
211/1129, CPCMH25-PO-1476486, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
213/1129, CPCMH25-PO-1476567, [], VEG
215/1129, CPCMH25-PO-1479174, [], VEG
217/1129, CPCMH25-PO-1479540, [], VEG
219/1129, CPCMH25-PO-1481820, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
221/1129, CPCMH25-PO-1482259, [], VEG
223/1129, CPCMH25-PO-1484570, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
225/1129, CPCMH25-PO-1485140, [], VEG
227/1129, CPCMH25-PO-1485423, [], VEG
229/1129, CPCMH25-PO-1487265, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
231/1129, CPCMH25-PO-1489848, [], VEG
233/1129, CPCMH25-PO-1490342, [], VEG
235/1129, CPCMH25-PO-1492227, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
237/1129, CPCMH25-PO-1495234, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
239/1129, CPCMH25-PO-1497948, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
241/1129, CPCMH25-PO-1500605, [], VEG
243/1129, CPCMH25-PO-1503447, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
245/1129, CPCMH25-PO-1506284, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
247/1129, CPCMH25-PO-1508673, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
249/1129, CPCMH25-PO-1510891, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
251/1129, CPCMH25-PO-1511707, [], VEG
252/1129, CPCMH25-PO-1513957, [], VEG
254/1129, CPCMH25-PO-1517146, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
256/1129, CPCMH25-PO-1520155, ['BH-Pumpkin Cut, 250 gm', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
258/1129, CPCMH25-PO-1520675, ['BH-Drumstick - Cut, 200 gm', 'BH-Jackfruit (Kathal) - Cut, 200 gm'], CUT-VEG
259/1129, CPCMH25-PO-1522206, ['BH-Cut Sambhar Mix, 200 gm', 'BH-Drumstick - Cut, 200 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
261/1129, CPCMH25-PO-1524969, ['BH-Cut Sambhar Mix, 200 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
263/1129, CPCMH25-PO-1527244, ['BH-Cut Sambhar Mix, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
265/1129, CPCMH25-PO-1529519, ['BH-Pumpkin Cut, 250 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
267/1129, CPCMH25-PO-1532557, [], VEG
269/1129, CPCMH25-PO-1533069, ['BH - Bitter Gourd - Cut, 250', 'BH-Pumpkin Cut, 250 gm', 'BH-Drumstick - Cut, 200 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
271/1129, CPCMH25-PO-1535398, [], VEG
273/1129, CPCMH25-PO-1535440, ['BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
275/1129, CPCMH25-PO-1538200, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Cut Sambhar Mix, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
277/1129, CPCMH25-PO-1538201, [], VEG
279/1129, CPCMH25-PO-1540997, ['BH-Pumpkin Cut, 250 gm', 'BH-Drumstick - Cut, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
281/1129, CPCMH25-PO-1543689, ['BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
283/1129, CPCMH25-PO-1543724, [], VEG
285/1129, CPCMH25-PO-1546142, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Pumpkin Cut, 250 gm', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
287/1129, CPCMH25-PO-1546145, [], VEG
289/1129, CPCMH25-PO-1548414, ['BH-Cut Sambhar Mix, 200 gm', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
291/1129, CPCMH25-PO-1548417, [], VEG
293/1129, CPCMH25-PO-1551436, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
295/1129, CPCMH25-PO-1551490, ['BH-Drumstick - Cut, 200 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
297/1129, CPCMH25-PO-1554119, [], VEG
299/1129, CPCMH25-PO-1554224, ['BH-Jackfruit (Kathal) - Cut,', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
301/1129, CPCMH25-PO-1557045, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
303/1129, CPCMH25-PO-1557090, [], VEG
305/1129, CPCMH25-PO-1560083, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
307/1129, CPCMH25-PO-1560113, [], VEG
309/1129, CPCMH25-PO-1562675, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
311/1129, CPCMH25-PO-1562784, [], VEG
313/1129, CPCMH25-PO-1565077, [], VEG
315/1129, CPCMH25-PO-1565099, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
317/1129, CPCMH25-PO-1567364, [], VEG
319/1129, CPCMH25-PO-1567492, ['BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
321/1129, CPCMH25-PO-1568149, [], VEG
322/1129, CPCMH26-PO-1570449, [], VEG
324/1129, CPCMH26-PO-1570461, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
326/1129, CPCMH26-PO-1573292, [], VEG
328/1129, CPCMH26-PO-1576063, [], VEG
330/1129, CPCMH26-PO-1579030, [], VEG
332/1129, CPCMH26-PO-1581975, [], VEG
334/1129, CPCMH26-PO-1584616, [], VEG
336/1129, CPCMH26-PO-1587087, [], VEG
338/1129, CPCMH26-PO-1587090, [], VEG
340/1129, CPCMH26-PO-1590125, ['BH-Drumstick - Cut, 200 gm'], CUT-VEG
342/1129, CPCMH26-PO-1590128, [], VEG
344/1129, CPCMH26-PO-1593143, ['BH-Drumstick - Cut, 200 gm'], CUT-VEG
346/1129, CPCMH26-PO-1596124, ['BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
348/1129, CPCMH26-PO-1596128, [], VEG
350/1129, CPCMH26-PO-1599075, ['BH-Drumstick - Cut, 200 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
352/1129, CPCMH26-PO-1602106, ['BH-Drumstick - Cut, 200 gm'], CUT-VEG
354/1129, CPCMH26-PO-1602108, ['BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
356/1129, CPCMH26-PO-1604950, ['BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
358/1129, CPCMH26-PO-1604953, [], VEG
360/1129, CPCMH26-PO-1607422, ['BH-Jackfruit (Kathal) - Cut,', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
362/1129, CPCMH26-PO-1607436, [], VEG
364/1129, CPCMH26-PO-1610550, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
366/1129, CPCMH26-PO-1610555, [], VEG
368/1129, CPCMH26-PO-1613650, [], VEG
370/1129, CPCMH26-PO-1613658, ['BH-Drumstick - Cut, 200 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
372/1129, CPCMH26-PO-1616801, ['BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
374/1129, CPCMH26-PO-1616803, [], VEG
376/1129, CPCMH26-PO-1619919, ['BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
378/1129, CPCMH26-PO-1622909, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
380/1129, CPCMH26-PO-1622911, [], VEG
382/1129, CPCMH26-PO-1625617, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
384/1129, CPCMH26-PO-1625619, [], VEG
386/1129, CPCMH26-PO-1628113, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
388/1129, CPCMH26-PO-1628115, [], VEG
390/1129, CPCMH26-PO-1629343, [], VEG
392/1129, CPCMH26-PO-1631446, ['BH-Pumpkin Cut, 250 gm'], CUT-VEG
394/1129, CPCMH26-PO-1631447, [], VEG
396/1129, CPCMH26-PO-1634709, [], VEG
398/1129, CPCMH26-PO-1634713, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
400/1129, CPCMH26-PO-1637785, [], VEG
402/1129, CPCMH26-PO-1638632, [], VEG
403/1129, CPCMH26-PO-1638892, [], VEG
405/1129, CPCMH26-PO-1641121, [], VEG
407/1129, CPCMH26-PO-1644259, [], VEG
409/1129, CPCMH26-PO-1647151, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
411/1129, CPCMH26-PO-1647159, [], VEG
413/1129, CPCMH26-PO-1647927, [], VEG
415/1129, CPCMH26-PO-1649726, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
417/1129, CPCMH26-PO-1649732, [], VEG
419/1129, CPCMH26-PO-1653102, [], VEG
421/1129, CPCMH26-PO-1653111, ['BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
423/1129, CPCMH26-PO-1654306, [], VEG
425/1129, CPCMH26-PO-1656179, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
427/1129, CPCMH26-PO-1656190, [], VEG
429/1129, CPCMH26-PO-1659257, [], VEG
431/1129, CPCMH26-PO-1659259, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
433/1129, CPCMH26-PO-1662589, ['BH-Drumstick - Cut, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
435/1129, CPCMH26-PO-1666354, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
437/1129, CPCMH26-PO-1666357, [], VEG
439/1129, CPCMH26-PO-1667170, [], VEG
441/1129, CPCMH26-PO-1669215, ['BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
443/1129, CPCMH26-PO-1669231, [], VEG
445/1129, CPCMH26-PO-1672144, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
447/1129, CPCMH26-PO-1672147, [], VEG
449/1129, CPCMH26-PO-1675614, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
451/1129, CPCMH26-PO-1675620, [], VEG
453/1129, CPCMH26-PO-1679006, [], VEG
455/1129, CPCMH26-PO-1679010, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
457/1129, CPCMH26-PO-1682230, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
459/1129, CPCMH26-PO-1682237, [], VEG
461/1129, CPCMH26-PO-1682617, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
463/1129, CPCMH26-PO-1685641, ['BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
465/1129, CPCMH26-PO-1685648, [], VEG
467/1129, CPCMH26-PO-1689087, ['BH-Jackfruit (Kathal) - Cut,', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
469/1129, CPCMH26-PO-1689093, [], VEG
471/1129, CPCMH26-PO-1691993, ['BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
473/1129, CPCMH26-PO-1691998, [], VEG
475/1129, CPCMH26-PO-1694635, ['BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
477/1129, CPCMH26-PO-1694643, [], VEG
479/1129, CPCMH26-PO-1695233, [], VEG
481/1129, CPCMH26-PO-1697992, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
483/1129, CPCMH26-PO-1697997, [], VEG
485/1129, CPCMH26-PO-1701658, [], VEG
487/1129, CPCMH26-PO-1701666, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
489/1129, CPCMH26-PO-1705019, [], VEG
491/1129, CPCMH26-PO-1705024, ['BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
493/1129, CPCMH26-PO-1708467, ['BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
495/1129, CPCMH26-PO-1708472, [], VEG
497/1129, CPCMH26-PO-1711801, [], VEG
499/1129, CPCMH26-PO-1711804, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
501/1129, CPCMH26-PO-1712272, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
503/1129, CPCMH26-PO-1714625, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
505/1129, CPCMH26-PO-1714631, [], VEG
507/1129, CPCMH26-PO-1717283, [], VEG
509/1129, CPCMH26-PO-1717289, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
511/1129, CPCMH26-PO-1720747, [], VEG
513/1129, CPCMH26-PO-1720755, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
515/1129, CPCMH26-PO-1724126, [], VEG
517/1129, CPCMH26-PO-1724133, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
519/1129, CPCMH26-PO-1727241, [], VEG
521/1129, CPCMH26-PO-1727246, [], VEG
523/1129, CPCMH26-PO-1730616, [], VEG
525/1129, CPCMH26-PO-1730622, ['BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm'], CUT-VEG
527/1129, CPCMH26-PO-1731117, ['BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
529/1129, CPCMH26-PO-1733947, [], VEG
531/1129, CPCMH26-PO-1733949, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Pumpkin Cut, 250 gm', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
533/1129, CPCMH26-PO-1736961, [], VEG
535/1129, CPCMH26-PO-1736966, ['BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
537/1129, CPCMH26-PO-1737316, [], VEG
539/1129, CPCMH26-PO-1739640, [], VEG
541/1129, CPCMH26-PO-1739644, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG

EOF marker not found

643/1129, CPCMH26-PO-1804198, [], VEG
645/1129, CPCMH26-PO-1804203, [], Error
647/1129, CPCMH26-PO-1806887, [], VEG
649/1129, CPCMH26-PO-1807636, [], VEG
651/1129, CPCMH26-PO-1807644, ['BH- Green Pumpkin Cut, 250'], CUT-VEG
653/1129, CPCMH26-PO-1808108, [], VEG
655/1129, CPCMH26-PO-1810250, [], VEG
657/1129, CPCMH26-PO-1810731, [], VEG
659/1129, CPCMH26-PO-1810737, ['BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
661/1129, CPCMH26-PO-1811485, [], VEG
663/1129, CPCMH26-PO-1814172, [], VEG
665/1129, CPCMH26-PO-1814732, [], VEG
667/1129, CPCMH26-PO-1814735, ['BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
669/1129, CPCMH26-PO-1817761, [], VEG
671/1129, CPCMH26-PO-1818527, [], VEG
673/1129, CPCMH26-PO-1818534, ['BH-Jackfruit (Kathal) - Cut,', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
675/1129, CPCMH26-PO-1820707, [], VEG
677/1129, CPCMH26-PO-1822151, [], VEG
679/1129, CPCMH26-PO-1822158, ['BH-Jackfruit (Kathal) - Cut,', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
681/1129, CPCMH26-PO-1825311, [], VEG
683/1129, CPCMH26-PO-1826066, [], VEG
685/1129, CPCMH26-PO-1826074, ['BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
687/1129, CPCMH26-PO-1826576, [], VEG
689/1129, CPCMH26-PO-1828648, [], VEG
691/1129, CPCMH26-PO-1829724, [], VEG
693/1129, CPCMH26-PO-1829726, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
695/1129, CPCMH26-PO-1832467, [], VEG
697/1129, CPCMH26-PO-1833311, [], VEG
699/1129, CPCMH26-PO-1833313, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
701/1129, CPCMH26-PO-1835171, [], VEG
703/1129, CPCMH26-PO-1836463, [], VEG
705/1129, CPCMH26-PO-1836467, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
707/1129, CPCMH26-PO-1837059, [], VEG
709/1129, CPCMH26-PO-1839279, [], VEG
711/1129, CPCMH26-PO-1840403, [], VEG
713/1129, CPCMH26-PO-1840412, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
715/1129, CPCMH26-PO-1840952, [], VEG
717/1129, CPCMH26-PO-1843348, [], VEG
719/1129, CPCMH26-PO-1844219, [], VEG
721/1129, CPCMH26-PO-1844225, ['BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
723/1129, CPCMH26-PO-1847188, [], VEG
725/1129, CPCMH26-PO-1848059, [], VEG
726/1129, CPCMH26-PO-1848063, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
728/1129, CPCMH26-PO-1848426, [], VEG
730/1129, CPCMH26-PO-1850921, [], VEG
732/1129, CPCMH26-PO-1851897, [], VEG
734/1129, CPCMH26-PO-1851903, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
736/1129, CPCMH26-PO-1852529, [], VEG
738/1129, CPCMH26-PO-1854403, [], VEG
740/1129, CPCMH26-PO-1855794, [], VEG
742/1129, CPCMH26-PO-1855798, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
744/1129, CPCMH26-PO-1857539, [], VEG
746/1129, CPCMH26-PO-1859131, [], VEG
748/1129, CPCMH26-PO-1859145, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
750/1129, CPCMH26-PO-1859147, [], VEG
752/1129, CPCMH26-PO-1861293, [], VEG
754/1129, CPCMH26-PO-1862347, [], VEG
756/1129, CPCMH26-PO-1862354, ['BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
758/1129, CPCMH26-PO-1865592, [], VEG
760/1129, CPCMH26-PO-1866158, [], VEG
762/1129, CPCMH26-PO-1866160, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
764/1129, CPCMH26-PO-1868365, [], VEG
766/1129, CPCMH26-PO-1869859, [], VEG
768/1129, CPCMH26-PO-1869868, ['BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
770/1129, CPCMH26-PO-1872542, [], VEG
772/1129, CPCMH26-PO-1873811, [], VEG
774/1129, CPCMH26-PO-1873815, ['BH-Jackfruit (Kathal) - Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
776/1129, CPCMH26-PO-1876535, [], VEG
778/1129, CPCMH26-PO-1877807, [], VEG
780/1129, CPCMH26-PO-1877819, [], VEG
782/1129, CPCMH26-PO-1877821, [], VEG
784/1129, CPCMH26-PO-1880458, [], VEG
786/1129, CPCMH26-PO-1880510, [], VEG
788/1129, CPCMH26-PO-1881537, [], VEG
790/1129, CPCMH26-PO-1881542, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
791/1129, CPCMH26-PO-1884249, [], VEG
793/1129, CPCMH26-PO-1885133, [], VEG
795/1129, CPCMH26-PO-1885137, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
797/1129, CPCMH26-PO-1887584, [], VEG
799/1129, CPCMH26-PO-1888399, [], VEG
801/1129, CPCMH26-PO-1888405, [], VEG
803/1129, CPCMH26-PO-1891642, [], VEG
805/1129, CPCMH26-PO-1892504, [], VEG
807/1129, CPCMH26-PO-1892511, [], VEG
809/1129, CPCMH26-PO-1892994, [], VEG
811/1129, CPCMH26-PO-1893283, [], VEG
813/1129, CPCMH26-PO-1895425, [], VEG
815/1129, CPCMH26-PO-1896357, [], VEG
817/1129, CPCMH26-PO-1896362, [], VEG

EOF marker not found
EOF marker not found

819/1129, CPCMH26-PO-1899269, [], VEG
820/1129, CPCMH26-PO-1900179, [], Error
822/1129, CPCMH26-PO-1900186, [], Error
824/1129, CPCMH26-PO-1904132, [], VEG
826/1129, CPCMH26-PO-1904138, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
828/1129, CPCMH26-PO-1908056, [], VEG
830/1129, CPCMH26-PO-1908398, [], VEG
832/1129, CPCMH26-PO-1911819, [], VEG
834/1129, CPCMH26-PO-1911830, [], VEG
836/1129, CPCMH26-PO-1915082, [], VEG
838/1129, CPCMH26-PO-1915191, ['BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
840/1129, CPCMH26-PO-1919136, [], VEG
842/1129, CPCMH26-PO-1919598, ['BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
844/1129, CPCMH26-PO-1923091, [], VEG
846/1129, CPCMH26-PO-1923097, ['BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
848/1129, CPCMH26-PO-1923110, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
850/1129, CPCMH26-PO-1927051, [], VEG
852/1129, CPCMH26-PO-1927055, ['BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
854/1129, CPCMH26-PO-1931007, [], VEG
856/1129, CPCMH26-PO-1931010, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
858/1129, CPCMH26-PO-1934932, [], VEG
860/1129, CPCMH26-PO-1934937, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
862/1129, CPCMH26-PO-1935681, [], VEG
864/1129, CPCMH26-PO-1938484, [], VEG
866/1129, CPCMH26-PO-1938486, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
868/1129, CPCMH26-PO-1941744, [], VEG
870/1129, CPCMH26-PO-1941748, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
872/1129, CPCMH26-PO-1946196, [], VEG
874/1129, CPCMH26-PO-1946206, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
876/1129, CPCMH26-PO-1950070, [], VEG
878/1129, CPCMH26-PO-1950076, ['BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
880/1129, CPCMH26-PO-1953978, [], VEG
882/1129, CPCMH26-PO-1953988, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
884/1129, CPCMH26-PO-1958173, [], VEG
886/1129, CPCMH26-PO-1958182, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
888/1129, CPCMH26-PO-1962179, [], VEG
890/1129, CPCMH26-PO-1962185, ['BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
892/1129, CPCMH26-PO-1966002, [], VEG
894/1129, CPCMH26-PO-1966009, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
896/1129, CPCMH26-PO-1969478, [], VEG
898/1129, CPCMH26-PO-1969483, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
900/1129, CPCMH26-PO-1973850, [], VEG
902/1129, CPCMH26-PO-1973855, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
904/1129, CPCMH26-PO-1977770, [], VEG
906/1129, CPCMH26-PO-1977773, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
908/1129, CPCMH26-PO-1981770, [], VEG
910/1129, CPCMH26-PO-1981780, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,'], CUT-VEG
912/1129, CPCMH26-PO-1985802, [], VEG
914/1129, CPCMH26-PO-1985811, ['BH- Green Pumpkin Cut, 250', 'BH-Jackfruit (Kathal) - Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
916/1129, CPCMH26-PO-1990163, [], VEG
918/1129, CPCMH26-PO-1990174, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
920/1129, CPCMH26-PO-1991116, [], VEG
922/1129, CPCMH26-PO-1993927, [], VEG
924/1129, CPCMH26-PO-1993933, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
926/1129, CPCMH26-PO-1997340, [], VEG
928/1129, CPCMH26-PO-1997350, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
930/1129, CPCMH26-PO-2001778, [], VEG
932/1129, CPCMH26-PO-2001782, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
934/1129, CPCMH26-PO-2005908, [], VEG
936/1129, CPCMH26-PO-2005914, ['BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
938/1129, CPCMH26-PO-2010110, [], VEG
940/1129, CPCMH26-PO-2010122, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
942/1129, CPCMH26-PO-2014522, [], VEG
944/1129, CPCMH26-PO-2014531, ['BH-French Fresh Beans Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH-Drumstick - Cut, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
946/1129, CPCMH26-PO-2018617, [], VEG
948/1129, CPCMH26-PO-2018621, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-French Fresh Beans Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
950/1129, CPCMH26-PO-2022093, [], VEG
952/1129, CPCMH26-PO-2022103, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-French Fresh Beans Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
954/1129, CPCMH26-PO-2025282, [], VEG
956/1129, CPCMH26-PO-2025283, ['BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
958/1129, CPCMH26-PO-2029682, [], VEG
960/1129, CPCMH26-PO-2029692, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH-French Fresh Beans Cut,'], CUT-VEG
962/1129, CPCMH26-PO-2033861, [], VEG
964/1129, CPCMH26-PO-2033863, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
966/1129, CPCMH26-PO-2038083, [], VEG
968/1129, CPCMH26-PO-2038089, ['BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
970/1129, CPCMH26-PO-2042494, [], VEG
972/1129, CPCMH26-PO-2042502, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-French Fresh Beans Cut,', 'BH - Bitter Gourd - Cut, 250', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
974/1129, CPCMH26-PO-2046348, [], VEG
976/1129, CPCMH26-PO-2046356, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH-French Fresh Beans Cut,', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
978/1129, CPCMH26-PO-2049885, [], VEG
980/1129, CPCMH26-PO-2049889, ['BH-Cut Sambhar Mix, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,'], CUT-VEG
982/1129, CPCMH26-PO-2053142, [], VEG
984/1129, CPCMH26-PO-2053149, ['BH-Cut Sambhar Mix, 200 gm', 'BH-French Fresh Beans Cut,', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
986/1129, CPCMH26-PO-2057391, [], VEG
988/1129, CPCMH26-PO-2057400, ['BH-Drumstick - Cut, 200 gm', 'BH-Cut Sambhar Mix, 200 gm', 'BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
990/1129, CPCMH26-PO-2061472, [], VEG
992/1129, CPCMH26-PO-2061476, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH-French Fresh Beans Cut,', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
994/1129, CPCMH26-PO-2065499, [], VEG
996/1129, CPCMH26-PO-2065507, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-French Fresh Beans Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
998/1129, CPCMH26-PO-2070086, [], VEG
1000/1129, CPCMH26-PO-2070089, [], VEG
1002/1129, CPCMH26-PO-2074255, [], VEG
1004/1129, CPCMH26-PO-2074257, ['BH-Cut Sambhar Mix, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,'], CUT-VEG
1006/1129, CPCMH26-PO-2077993, [], VEG
1008/1129, CPCMH26-PO-2078006, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250', 'BH-French Fresh Beans Cut,', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
1010/1129, CPCMH26-PO-2081612, [], VEG
1012/1129, CPCMH26-PO-2081622, ['BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,'], CUT-VEG
1014/1129, CPCMH26-PO-2086191, [], VEG
1016/1129, CPCMH26-PO-2086200, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250', 'BH-French Fresh Beans Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
1018/1129, CPCMH26-PO-2090555, [], VEG
1020/1129, CPCMH26-PO-2090564, ['BH-Cut Sambhar Mix, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,'], CUT-VEG
1022/1129, CPCMH26-PO-2094510, [], VEG
1024/1129, CPCMH26-PO-2094520, ['BH-Drumstick - Cut, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-French Fresh Beans Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1026/1129, CPCMH26-PO-2098458, [], VEG
1028/1129, CPCMH26-PO-2098469, ['BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,'], CUT-VEG
1030/1129, CPCMH26-PO-2102514, [], VEG
1032/1129, CPCMH26-PO-2102518, ['BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1034/1129, CPCMH26-PO-2106212, [], VEG
1036/1129, CPCMH26-PO-2106226, ['BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
1038/1129, CPCMH26-PO-2109709, [], VEG
1040/1129, CPCMH26-PO-2109715, ['BH - Bitter Gourd - Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1042/1129, CPCMH26-PO-2114274, [], VEG
1044/1129, CPCMH26-PO-2114282, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
1046/1129, CPCMH26-PO-2118474, [], VEG
1048/1129, CPCMH26-PO-2118480, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-French Fresh Beans Cut,', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1050/1129, CPCMH26-PO-2122452, [], VEG
1052/1129, CPCMH26-PO-2122458, ['BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
1054/1129, CPCMH26-PO-2126789, [], VEG
1056/1129, CPCMH26-PO-2126796, ['BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1058/1129, CPCMH26-PO-2131275, [], VEG
1060/1129, CPCMH26-PO-2131284, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
1062/1129, CPCMH26-PO-2135000, [], VEG
1064/1129, CPCMH26-PO-2135022, ['BH-French Fresh Beans Cut,', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
1066/1129, CPCMH26-PO-2138373, [], VEG
1068/1129, CPCMH26-PO-2138378, ['BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
1070/1129, CPCMH26-PO-2142966, [], VEG
1072/1129, CPCMH26-PO-2142971, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH-French Fresh Beans Cut,', 'BH- Green Pumpkin Cut, 250', 'BH-Cut Sambhar Mix, 200 gm'], CUT-VEG
1074/1129, CPCMH26-PO-2147260, [], VEG
1076/1129, CPCMH26-PO-2151385, [], VEG
1078/1129, CPCMH26-PO-2155663, [], VEG
1080/1129, CPCMH26-PO-2159777, ['BH- Green Pumpkin Cut, 250'], CUT-VEG
1082/1129, CPCMH26-PO-2163628, ['BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
1084/1129, CPCMH26-PO-2167138, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1086/1129, CPCMH26-PO-2171680, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1088/1129, CPCMH26-PO-2175866, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1090/1129, CPCMH26-PO-2180091, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1092/1129, CPCMH26-PO-2184466, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1094/1129, CPCMH26-PO-2188648, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1096/1129, CPCMH26-PO-2192773, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1098/1129, CPCMH26-PO-2196557, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
1100/1129, CPCMH26-PO-2201414, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1102/1129, CPCMH26-PO-2206334, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
1104/1129, CPCMH26-PO-2210576, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
1106/1129, CPCMH26-PO-2215118, ['BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
1108/1129, CPCMH26-PO-2219432, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1110/1129, CPCMH26-PO-2223432, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
1112/1129, CPCMH26-PO-2227057, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1114/1129, CPCMH26-PO-2231953, ['BH- Green Pumpkin Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
1116/1129, CPCMH26-PO-2236408, ['BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1118/1129, CPCMH26-PO-2240712, ['BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
1120/1129, CPCMH26-PO-2244427, ['BH-Drumstick - Cut, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1122/1129, CPCMH26-PO-2248894, ['BH-Drumstick - Cut, 200 gm', 'BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250'], CUT-VEG
1124/1129, CPCMH26-PO-2252935, ['BH - Bitter Gourd - Cut, 250', 'BH- Green Pumpkin Cut, 250', 'BH-Drumstick - Cut, 200 gm'], CUT-VEG
1126/1129, CPCMH26-PO-2256775, ['BH-Drumstick - Cut, 200 gm', 'BH- Green Pumpkin Cut, 250', 'BH - Bitter Gourd - Cut, 250'], CUT-VEG
1128/1129, CPCMH26-PO-2256779, ['BH-French Fresh Beans Cut,'], CUT-VEG

In [37]:
grnPrDF

,PO Number,Cut/Veg,Date,GRN,PO Amount.1,Error
PO Amount,,,,,,
CPCMH25-PO-1269666,CPCMH25-PO-1269666,VEG,05-12-2024,18788.5,18806.0,NaN
CPCMH25-PO-1274368,CPCMH25-PO-1274368,CUT-VEG,07-12-2024,3679.5,3679.5,NaN
CPCMH25-PO-1276694,CPCMH25-PO-1276694,CUT-VEG,08-12-2024,12899.5,12956.5,NaN
CPCMH25-PO-1279272,CPCMH25-PO-1279272,VEG,09-12-2024,9014.0,9028.0,NaN
CPCMH25-PO-1281280,CPCMH25-PO-1281280,CUT-VEG,10-12-2024,52301.7,55274.2,NaN
...,...,...,...,...,...,...
CPCMH26-PO-2244427,CPCMH26-PO-2244427,CUT-VEG,03-10-2025,7863.0,15268.5,list index out of range;;
CPCMH26-PO-2248894,CPCMH26-PO-2248894,CUT-VEG,04-10-2025,14854.4,26797.0,list index out of range;;
CPCMH26-PO-2252935,CPCMH26-PO-2252935,CUT-VEG,05-10-2025,17686.8,23482.2,list index out of range;;
CPCMH26-PO-2256775,CPCMH26-PO-2256775,CUT-VEG,06-10-2025,19440.0,23255.0,list index out of range;;
CPCMH26-PO-2256779,CPCMH26-PO-2256779,CUT-VEG,06-10-2025,13247.0,20202.0,list index out of range;;

In [ ]:
mail.logout()

In [ ]:
grnPrDF["PR"] = grnPrDF["PO Amount"] - grnPrDF["GRN"]

In [ ]:
toSave = grnPrDF[["Cut/Veg", "Date", "GRN", "PR", "PO Amount"]]

In [46]:
toSave.index.name = "PO Number"

In [47]:
toSave.to_csv("GRN PR (Blinkit).csv", index=True)